export const API_BASE = "https://ads-backend-4ho2.onrender.com";

export const endpoints = {
  ADMIN_LOGIN: "/site_admin/auth/admin/login/",
  GET_ADMIN: "/site_admin/auth/admin/me/",
  REFRESH: "/auth/refresh-token/",
  PATCH_PROFILE: "/auth/update_profile/",
  CHANGE_PASSWORD: "/auth/user_change_password/",
  CHANGE_TXN_PASSWORD: "/auth/user_change_transactional_password/",
  DEPOSITS: "/site_admin/deposits/",
  DEPOSIT_STATUS: (id) => `/site_admin/deposits/${id}/update-status/`,
  EVENTS: "/site_admin/events/",
  EVENT: (id) => `/site_admin/events/${id}/`,
  ANNOUNCEMENTS: "/site_admin/announcements/",
  ANNOUNCEMENT: (id) => `/site_admin/announcements/${id}/`,
  SETTINGS: "/site_admin/settings/",
  PATCH_SETTINGS: "/site_admin/settings/update-settings/",
  POST_VIDEO: "/site_admin/settings/update-video/",
  PACKS: "/api/packs/",
  PACK: (id) => `/api/packs/${id}/`,
  PRODUCTS: "/api/products/",
  PRODUCT: (id) => `/api/products/${id}/`,
  USERS: "/site_admin/users/",
  GENERATE_CODE: "/auth/invitation-codes/generate-code/",
  REFERRALS: "/site_admin/referrals/",
  SPECIAL_LINK: "/site_admin/referrals/special-link/",
  UPDATE_LOGIN_PASSWORD: "/site_admin/users/update-login-password/",
  UPDATE_WITHDRAWAL_PASSWORD: "/site_admin/users/update-withdrawal-password/",
  UPDATE_BALANCE: "/site_admin/users/update-balance/",
  UPDATE_PROFIT: "/site_admin/users/update-profit/",
  UPDATE_SALARY: "/site_admin/users/update-salary/",
  TOGGLE_REG_BONUS: "/site_admin/users/toggle-reg-bonus/",
  TOGGLE_MIN_BALANCE: "/site_admin/users/toggle-min-balance/",
  USER_INFO: "/site_admin/users/get_user_info/",
  TOGGLE_ACTIVE: "/site_admin/users/toggle_user_active/",
  UPDATE_CREDIT: "/site_admin/users/update_credit_score/",
  UPDATE_PACKAGE: "/site_admin/users/update-package/",
  UPDATE_MISSIONS: "/site_admin/users/update-missions/",
  UPDATE_ON_HOLD: "/site_admin/users/update-on-hold/",
  CREATE_USER: "/site_admin/users/create/",
  RESET_ACCOUNT: "/site_admin/users/reset_user_account/",
  DELETE_USER: "/site_admin/users/delete-user/",
  NEGATIVE_USERS: "/site_admin/negative-users/",
  NEGATIVE_USER: (id) => `/site_admin/negative-users/${id}/`,
  TOGGLE_NEGATIVE: (id) => `/site_admin/negative-users/${id}/toggle/`,
  ON_HOLDS: "/site_admin/onholds/",
  USER_HOLDS: "/site_admin/user-holds/",
  ON_HOLD: (id) => `/site_admin/onholds/${id}/`,
  WITHDRAWALS: "/site_admin/withdrawals/",
  WITHDRAWAL_STATUS: (id) => `/site_admin/withdrawals/${id}/update-status/`,
  NOTIFICATIONS: "/api/admin-notifications/",
  MARK_ALL_READ: "/api/admin-notifications/mark-all-read/",
  MARK_READ: "/api/admin-notifications/mark-read/",
  LOGS: "/api/admin-logs/",
};
